In [1]:
import pickle
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
data = {'data': iris.data, 'target': iris.target}

# Save the Iris dataset to a pickle file
with open("iris_data.pkl", "wb") as file:
    pickle.dump(data, file)

print("Iris dataset saved as 'iris_data.pkl'")

# Print the shape and a sample of the data to inspect it
print(f"Shape of X (features): {iris.data.shape}")
print(f"Sample of features (X): {iris.data[:5]}")  # First 5 rows of the data
print(f"Target labels (y): {iris.target[:5]}")  # First 5 target labels


Iris dataset saved as 'iris_data.pkl'
Shape of X (features): (150, 4)
Sample of features (X): [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Target labels (y): [0 0 0 0 0]


In [ ]:
import pickle
import numpy as np

# Load the pickle file containing the Iris dataset
with open("iris_data.pkl", "rb") as file:
    data = pickle.load(file)

# Extract features and target labels from the loaded data
X = data['data']
y = data['target']

# Print the shape and a sample of the data to check
print(f"Shape of X (features): {X.shape}")
print(f"Sample of features (X): {X[:5]}")  # First 5 rows of the data
print(f"Target labels (y): {y[:5]}")  # First 5 target labels

# Let's add new data (e.g., one new sample of 4 features) and check the output
new_data = np.array([[5.1, 3.5, 1.4, 0.2]])  # New sample
new_prediction = np.array([0])  # Corresponding target label (e.g., class 0)

# Append the new data to the existing dataset
X_new = np.vstack([X, new_data])  # Add new sample to feature data
y_new = np.append(y, new_prediction)  # Add new target label

# Print the updated data
print(f"Updated shape of X (features): {X_new.shape}")
print(f"Updated sample of features (X): {X_new[-5:]}")  # Last 5 rows of the data
print(f"Updated target labels (y): {y_new[-5:]}")  # Last 5 target labels
